
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_IIC_AVAGO_DEVICE_ID,
		XPAR_IIC_AVAGO_BASEADDR,
		XPAR_IIC_AVAGO_TEN_BIT_ADR,
		XPAR_IIC_AVAGO_GPO_WIDTH
	},
	{
		XPAR_IIC_CLK_DEVICE_ID,
		XPAR_IIC_CLK_BASEADDR,
		XPAR_IIC_CLK_TEN_BIT_ADR,
		XPAR_IIC_CLK_GPO_WIDTH
	}
};


